
service: server

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline


functions:
  users:
    handler: src/handler.getAllUsers
    events:
     - httpApi:
         path: /api/getAllUsers
         method: get